### ISSUE TITLE
Remove Useless Ranks

### ISSUE THREAD

**Issue by Hockeyfan360** [RubyFreedomDevelopmentTeam/RubyFreedomMod#13]
Such as, rubyfreedom developer, mysteri, horse, and soooo many others. Just add on to the tfm developers list, and rename that list to developers.

**Comment by reuben4545** [comment]
No, We cant do that otherwise it will just not work.

**Comment by Hockeyfan360** [comment]
Actually, we can.

**Comment by reuben4545** [comment]
I actually don't think so
