### ISSUE TITLE
Restart The Mod

### ISSUE THREAD

**Issue by Hockeyfan360** [RubyFreedomDevelopmentTeam/RubyFreedomMod#16]
This plugin is getting really damn messy, I suggest we start over and fix the mistakes made.

**Comment by mysteriace** [comment]
:-1

**Comment by mysteriace** [comment]
:-1:

**Comment by reuben4545** [comment]
Issue closed, also How is the plugin messy brah?

**Comment by Hockeyfan360** [comment]
@reuben4545 Just look at TFM_Playerrank

It is really, really messy. The code should be cleaner, and refracted. Also, we need to remove useless chat spam commands, etc.

**Comment by reuben4545** [comment]
Well, You might be right, I think we should actually restart the mod, But we SHOULD like save some of the command codes.

**Comment by DarkGamingDronze** [comment]
You mean a RFM:Revamped?

The answer is: no, we will not clean the mod (not until me/looper say)

**Comment by Hockeyfan360** [comment]
@DarkGamingDronze We don't need to remove all of the features, but the code is super messy. We need to at least go in and make some changes. Also, the constant commits to /al need to stop.

**Comment by ValenciaOrange** [comment]
I'l currently remaking the mod for the new rfreedom
