### ISSUE TITLE
Removing credit of myself is a threat

### ISSUE THREAD

**Issue by tylerhyperHD** [RubyFreedomDevelopmentTeam/RubyFreedomMod#3]
To me, if you remove credit on something that I committed and worked hard on, you are threatening me as a person. Re-add my credit to RFM because that is just a jerk move and I will press charges for that.

**Comment by Hockeyfan360** [comment]
I believe that this issue has been resolved. I made it clear to Valencia that I do not work for illicit organizations, and she added your credits back.
