### ISSUE TITLE
Harp Down on Libraries

### ISSUE THREAD

**Issue by Hockeyfan360** [RubyFreedomDevelopmentTeam/RubyFreedomMod#5]
I just looked at how many libraries you use for your plugins, and it is an overwhelmingly large amount. I highly suggest getting rid of things that you do not need.

**Comment by falceso** [comment]
Lel looper

**Comment by ValenciaOrange** [comment]
727c2c122ce6dad1bc995ba42a8895b170acda50

**Comment by ValenciaOrange** [comment]
C
